#  http://localhost:8086
server:
  port: 8086
logging:
  level:
    org.example.springexample: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportswear
    username: root
    password: 1eav
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: validate